from Crypto.PublicKey import RSA
from Crypto.Cipher import PKCS1_v1_5
pathfiles=['./1.pem','./2.pem','./3.pem','./4.pem','./5.pem','./6.pem','./7.pem','./8.pem']
plaintext=['arsalan','barazesh','onur','demir','nima','thoabe','berthold','busskamp']
k= RSA.importKey(open(pathfiles[0]))
cipher= PKCS1_v1_5.new(k)
ciphertext= cipher.encrypt(plaintext[0])
f = open ('1.bin', 'w')
f.write(ciphertext)
f.close()
k= RSA.importKey(open(pathfiles[1]))
cipher= PKCS1_v1_5.new(k)
ciphertext= cipher.encrypt(plaintext[1])
f = open ('2.bin', 'w')
f.write(ciphertext)
f.close()
k= RSA.importKey(open(pathfiles[2]))
cipher= PKCS1_v1_5.new(k)
ciphertext= cipher.encrypt(plaintext[2])
f = open ('3.bin', 'w')
f.write(ciphertext)
f.close()
k= RSA.importKey(open(pathfiles[3]))
cipher= PKCS1_v1_5.new(k)
ciphertext= cipher.encrypt(plaintext[3])
f = open ('4.bin', 'w')
f.write(ciphertext)
f.close()
k= RSA.importKey(open(pathfiles[4]))
cipher= PKCS1_v1_5.new(k)
ciphertext= cipher.encrypt(plaintext[4])
f = open ('5.bin', 'w')
f.write(ciphertext)
f.close()
k= RSA.importKey(open(pathfiles[5]))
cipher= PKCS1_v1_5.new(k)
ciphertext= cipher.encrypt(plaintext[5])
f = open ('6.bin', 'w')
f.write(ciphertext)
f.close()
k= RSA.importKey(open(pathfiles[6]))
cipher= PKCS1_v1_5.new(k)
ciphertext= cipher.encrypt(plaintext[6])
f = open ('7.bin', 'w')
f.write(ciphertext)
f.close()
k= RSA.importKey(open(pathfiles[7]))
cipher= PKCS1_v1_5.new(k)
ciphertext= cipher.encrypt(plaintext[7])
f = open ('8.bin', 'w')
f.write(ciphertext)
f.close()